# Generated by Django 3.0.6 on 2020-07-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('regd_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='institute.Institutestd')),
                ('dates', models.TextField()),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='outing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField()),
                ('fromTime', models.TimeField()),
                ('toDate', models.DateField()),
                ('toTime', models.TimeField()),
                ('purpose', models.CharField(max_length=150)),
                ('parent_mobile', models.BigIntegerField()),
                ('permission', models.CharField(choices=[('Pending', 'Pending'), ('Granted', 'Granted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('regd_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.Institutestd')),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('regd_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='institute.Institutestd')),
                ('room_no', models.IntegerField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, choices=[('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second')], max_length=10, null=True)),
                ('block_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.Blocks')),
            ],
        ),
    ]
