# Generated by Django 3.0.5 on 2020-04-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='permission',
            field=models.CharField(choices=[('Granted', 'Granted'), ('Rejected', 'Rejected')], default='Rejected', max_length=20),
        ),
        migrations.AddField(
            model_name='outing',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Active', 'Active'), ('Completed', 'Completed')], default='none', max_length=20),
            preserve_default=False,
        ),
    ]
