# Generated by Django 3.0.6 on 2020-09-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200916_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='dates',
        ),
        migrations.AddField(
            model_name='attendance',
            name='absent_dates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='present_dates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
