# Generated by Django 3.0.6 on 2020-12-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_document_feedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
