# Generated by Django 3.0.5 on 2020-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200429_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='floor',
            field=models.CharField(choices=[('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second')], default='Ground', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='room_no',
            field=models.IntegerField(),
        ),
    ]
