# Generated by Django 3.0.6 on 2020-09-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200919_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outing',
            name='fromTime',
        ),
        migrations.RemoveField(
            model_name='outing',
            name='toTime',
        ),
        migrations.AlterField(
            model_name='outing',
            name='fromDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='outing',
            name='toDate',
            field=models.DateTimeField(),
        ),
    ]
