# Generated by Django 3.0.6 on 2021-01-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_document_aadhar_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='floor',
            field=models.CharField(blank=True, choices=[('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=10, null=True),
        ),
    ]
