# Generated by Django 3.0.6 on 2021-01-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_auto_20210112_2117'),
        ('students', '0004_auto_20210111_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Block'),
        ),
    ]
