# Generated by Django 3.0.5 on 2020-04-29 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200429_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='toTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
