# Generated by Django 3.0.5 on 2020-04-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_outing_totime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outing',
            name='status',
        ),
    ]
