# Generated by Django 3.0.5 on 2020-05-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0008_auto_20200501_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('General', 'General'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Cleaning', 'Cleaning'), ('Indisciplinary', 'Indisciplinary'), ('Discrimination/Harassment', 'Discrimination/Harassment'), ('Damage to property', 'Damage to property')], max_length=40)),
                ('summary', models.CharField(max_length=200)),
                ('detailed', models.TextField()),
                ('complainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complainee', to='institute.Institutestd')),
                ('regd_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='institute.Institutestd')),
            ],
        ),
    ]
