# Generated by Django 3.0.6 on 2020-07-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('General', 'General'), ('Food Issues', 'Food Issues'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Room Cleaning', 'Room Cleaning'), ('Restroom Cleaning', 'Restroom Cleaning'), ('Indisciplinary', 'Indisciplinary'), ('Discrimination/Harassment', 'Discrimination/Harassment'), ('Damage to property', 'Damage to property'), ('Latecomer', 'Latecomer')], max_length=40)),
                ('summary', models.CharField(max_length=200)),
                ('detailed', models.TextField()),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Processing', 'Processing'), ('Resolved', 'Resolved')], default='Registered', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('complainee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offComplainee', to='institute.Institutestd')),
                ('regd_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offComplaints', to='institute.Officials')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('General', 'General'), ('Food Issues', 'Food Issues'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Room Cleaning', 'Room Cleaning'), ('Restroom Cleaning', 'Restroom Cleaning'), ('Indisciplinary', 'Indisciplinary'), ('Discrimination/Harassment', 'Discrimination/Harassment'), ('Damage to property', 'Damage to property')], max_length=40)),
                ('summary', models.CharField(max_length=200)),
                ('detailed', models.TextField()),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Processing', 'Processing'), ('Resolved', 'Resolved')], default='Registered', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('complainee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complainee', to='institute.Institutestd')),
                ('regd_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='institute.Institutestd')),
            ],
        ),
    ]
