# Generated by Django 3.0.5 on 2020-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Processing', 'Processing'), ('Resolved', 'Resolved')], default='Registered', max_length=20),
        ),
    ]
