# Generated by Django 3.0.5 on 2020-05-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaints_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
