# Generated by Django 3.0.5 on 2020-05-13 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_auto_20200501_1403'),
        ('complaints', '0007_auto_20200514_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complainee', to='institute.Institutestd'),
        ),
    ]
