# Generated by Django 3.0.5 on 2020-06-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_auto_20200522_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='officialcomplaints',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
