# Generated by Django 3.0.5 on 2020-06-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_auto_20200603_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialcomplaints',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
