# Generated by Django 3.0.6 on 2020-06-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_auto_20200605_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='type',
            field=models.CharField(choices=[('General', 'General'), ('Food Issues', 'Food Issues'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Room Cleaning', 'Room Cleaning'), ('Restroom Cleaning', 'Restroom Cleaning'), ('Indisciplinary', 'Indisciplinary'), ('Discrimination/ Harassment', 'Discrimination/ Harassment'), ('Damage to property', 'Damage to property')], max_length=40),
        ),
        migrations.AlterField(
            model_name='officialcomplaints',
            name='type',
            field=models.CharField(choices=[('General', 'General'), ('Food Issues', 'Food Issues'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Room Cleaning', 'Room Cleaning'), ('Restroom Cleaning', 'Restroom Cleaning'), ('Indisciplinary', 'Indisciplinary'), ('Discrimination/ Harassment', 'Discrimination/ Harassment'), ('Damage to property', 'Damage to property'), ('Latecomer', 'Latecomer')], max_length=40),
        ),
    ]
