# Generated by Django 3.0.5 on 2020-05-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
        ('institute', '0008_auto_20200501_1403'),
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.Workers'),
        ),
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together={('regd_no', 'emp_id', 'staff_id')},
        ),
    ]
