# Generated by Django 3.0.5 on 2020-05-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_medical'),
        ('institute', '0008_auto_20200501_1403'),
        ('authenticate', '0002_auto_20200514_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.Officials'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='regd_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.Institutestd'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.Workers'),
        ),
    ]
