# Generated by Django 3.0.5 on 2020-05-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0010_auto_20200522_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterCan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.Blocks')),
            ],
        ),
    ]
