# Generated by Django 3.0.6 on 2020-07-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutestd',
            fields=[
                ('regd_no', models.IntegerField(primary_key=True, serialize=False)),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronic and Communication Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('CHE', 'Chemical Engineering'), ('MME', 'Metalurgy Engineering'), ('MEC', 'Mechanical Engineering'), ('CIV', 'Civil Engineering'), ('BIO', 'Bio Technology')], max_length=3)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('pwd', models.BooleanField(default=True)),
                ('caste', models.CharField(choices=[('GEN', 'GEN'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], default='GEN', max_length=25)),
                ('year', models.IntegerField()),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=25)),
                ('email_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('parents_phone', models.CharField(max_length=10)),
                ('emergency_phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('is_hosteller', models.BooleanField(default=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('amount_paid', models.FloatField(blank=True, default=0, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=64, null=True)),
                ('dop', models.DateField(blank=True, null=True)),
                ('application', models.FileField(blank=True, null=True, upload_to='')),
                ('undertaking_form', models.FileField(blank=True, null=True, upload_to='')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='')),
                ('affidavit', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Officials',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Caretaker', 'Caretaker'), ('Warden', 'Warden'), ('Deputy Chief-Warden', 'Deputy Chief-Warden'), ('Chief-Warden', 'ChiefWarden')], max_length=20)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronic and Communication Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('CHE', 'Chemical Engineering'), ('MME', 'Metalurgy Engineering'), ('MEC', 'Mechanical Engineering'), ('CIV', 'Civil Engineering'), ('BIO', 'Bio Technology')], default='CSE', max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('block_id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('1S', 'One student per Room'), ('2S', 'Two students per Room'), ('4S', 'Four students per Room')], max_length=2)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('capacity', models.IntegerField()),
                ('emp_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.Officials')),
            ],
        ),
    ]
