# Generated by Django 3.0.5 on 2020-04-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutestd',
            fields=[
                ('regd_no', models.IntegerField(primary_key=True, serialize=False)),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronic and Communication Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('CHE', 'Chemical Engineering'), ('MME', 'Metalurgy Engineering'), ('MEC', 'Mechanical Engineering'), ('CIV', 'Civil Engineering')], max_length=3)),
                ('pwd', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('email_id', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('hosteller', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('paid', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Officials',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('CR', 'CareTakers'), ('WA', 'Wardens'), ('CW', 'ChiefWarden')], max_length=2)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email_id', models.CharField(max_length=50)),
            ],
        ),
    ]
