# Generated by Django 3.0.5 on 2020-04-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('1S', 'One student per Room'), ('2S', 'Two students per Room'), ('3S', 'Three students per Room')], max_length=2)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.Officials')),
            ],
        ),
    ]
