# Generated by Django 3.0.6 on 2020-07-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutestd',
            name='pwd',
            field=models.BooleanField(default=False),
        ),
    ]
