# Generated by Django 3.0.5 on 2020-04-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.Officials'),
        ),
    ]
