# Generated by Django 3.0.6 on 2020-07-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20200722_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutestd',
            name='year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
