# Generated by Django 3.0.5 on 2020-04-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_auto_20200429_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocks',
            name='id',
        ),
        migrations.AddField(
            model_name='blocks',
            name='block_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
