# Generated by Django 3.0.6 on 2020-07-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_auto_20200722_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutestd',
            old_name='caste',
            new_name='community',
        ),
    ]
