# Generated by Django 3.0.6 on 2020-07-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20200722_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutestd',
            name='has_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
