# Generated by Django 3.0.5 on 2020-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20200429_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
