# Generated by Django 3.0.6 on 2020-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_auto_20200722_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutestd',
            name='email_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='regd_no',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
