# Generated by Django 3.0.5 on 2020-04-30 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_blocks_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='emp_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute.Officials'),
        ),
    ]
