# Generated by Django 3.0.6 on 2020-12-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_auto_20201121_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
