# Generated by Django 3.0.5 on 2020-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_auto_20200430_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutestd',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7),
            preserve_default=False,
        ),
    ]
