# Generated by Django 3.0.6 on 2020-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_auto_20200723_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officials',
            name='email_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
