# Generated by Django 3.0.5 on 2020-05-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_auto_20200501_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officials',
            name='designation',
            field=models.CharField(choices=[('Caretaker', 'Caretaker'), ('Warden', 'Warden'), ('Deputy Chief-Warden', 'Deputy Chief-Warden'), ('Chief-Warden', 'ChiefWarden')], max_length=20),
        ),
    ]
