# Generated by Django 3.0.6 on 2020-07-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_auto_20200723_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officials',
            name='designation',
            field=models.CharField(choices=[('Caretaker', 'Caretaker'), ('Warden', 'Warden'), ('Deputy Chief-Warden', 'Deputy Chief-Warden'), ('Chief-Warden', 'Chief-Warden')], max_length=20),
        ),
    ]
