# Generated by Django 3.0.6 on 2021-01-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_auto_20210108_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='floor_count',
            field=models.IntegerField(default=3, verbose_name='No. of Floors'),
            preserve_default=False,
        ),
    ]
