# Generated by Django 3.0.5 on 2020-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_auto_20200522_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutestd',
            name='emr_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='ph_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='officials',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
