# Generated by Django 3.0.5 on 2020-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_auto_20200522_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='room_type',
            field=models.CharField(choices=[('1S', 'One student per Room'), ('2S', 'Two students per Room'), ('4S', 'Four students per Room')], max_length=2),
        ),
    ]
