# Generated by Django 3.0.5 on 2020-05-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0011_auto_20200528_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='emp_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.Officials'),
        ),
    ]
