# Generated by Django 3.0.5 on 2020-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0013_auto_20200529_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officials',
            name='address',
        ),
        migrations.AddField(
            model_name='officials',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronic and Communication Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('CHE', 'Chemical Engineering'), ('MME', 'Metalurgy Engineering'), ('MEC', 'Mechanical Engineering'), ('CIV', 'Civil Engineering'), ('BIO', 'Bio Technology')], default='CSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='afd',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='application',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronic and Communication Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('CHE', 'Chemical Engineering'), ('MME', 'Metalurgy Engineering'), ('MEC', 'Mechanical Engineering'), ('CIV', 'Civil Engineering'), ('BIO', 'Bio Technology')], max_length=3),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='pwd',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='recipt',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='undertake',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
