# Generated by Django 3.0.6 on 2020-07-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='email_id',
            field=models.CharField(default='test@hms.com', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
