# Generated by Django 3.0.6 on 2020-09-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20200919_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalIssue',
        ),
    ]
