# Generated by Django 3.0.5 on 2020-05-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20200514_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='email_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
