# Generated by Django 3.0.6 on 2021-01-08 09:26

from django.db import migrations, models
import institute.validators


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20201121_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=10, validators=[institute.validators.numeric_only]),
        ),
    ]
