# Generated by Django 3.0.5 on 2020-05-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('staff_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workers.Workers')),
                ('dates', models.TextField()),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
