# Generated by Django 3.0.5 on 2020-05-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='dates',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
