# Generated by Django 3.0.5 on 2020-06-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20200515_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
