# Generated by Django 3.0.5 on 2020-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_medical_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='address',
        ),
        migrations.AddField(
            model_name='workers',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
