# Generated by Django 3.0.5 on 2020-06-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_auto_20200603_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
